// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6Bbrws9h9AFELD9LNQFCaONgy0V0kaE',
    appId: '1:677943389995:android:a7956740e207c4b2e25f6e',
    messagingSenderId: '677943389995',
    projectId: 'beyoundthecall',
    storageBucket: 'beyoundthecall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQvpiUOvayp1pqCB2Lq87WB9qnrM6U_SI',
    appId: '1:677943389995:ios:980e7a2586dbfa3de25f6e',
    messagingSenderId: '677943389995',
    projectId: 'beyoundthecall',
    storageBucket: 'beyoundthecall.appspot.com',
    iosBundleId: 'com.example.brightminds',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR40cVlcYWeDeX4HuOoEDbE_cRQ3aJ9Ig',
    appId: '1:677943389995:web:1169627f02a2be74e25f6e',
    messagingSenderId: '677943389995',
    projectId: 'beyoundthecall',
    authDomain: 'beyoundthecall.firebaseapp.com',
    storageBucket: 'beyoundthecall.appspot.com',
    measurementId: 'G-65EXGQFLMR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQvpiUOvayp1pqCB2Lq87WB9qnrM6U_SI',
    appId: '1:677943389995:ios:980e7a2586dbfa3de25f6e',
    messagingSenderId: '677943389995',
    projectId: 'beyoundthecall',
    storageBucket: 'beyoundthecall.appspot.com',
    iosBundleId: 'com.example.brightminds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR40cVlcYWeDeX4HuOoEDbE_cRQ3aJ9Ig',
    appId: '1:677943389995:web:ee4171f68461c558e25f6e',
    messagingSenderId: '677943389995',
    projectId: 'beyoundthecall',
    authDomain: 'beyoundthecall.firebaseapp.com',
    storageBucket: 'beyoundthecall.appspot.com',
    measurementId: 'G-WTDB16WD38',
  );

}